const fs=require('fs');const setup=require('./replay.test.js');
(async()=>{const {b,p}=await setup();const L=(...a)=>console.log(...a.map(x=>typeof x==='string'?x:JSON.stringify(x)));
  const ids=await p.evaluate(()=>({tan:S.clients.find(c=>/Tan/.test(c.name)).id,pat:S.clients.find(c=>/Patel/.test(c.name)).id}));
  await p.evaluate(id=>go('client',{id,tab:'profile'}),ids.tan);await p.screenshot({path:'F-profile.png',fullPage:true});
  await p.evaluate(id=>go('client',{id}),ids.tan);await p.screenshot({path:'F-client.png',fullPage:true});
  const dl=async(sel,name)=>{const [d]=await Promise.all([p.waitForEvent('download'),p.click(sel)]);await d.saveAs(__dirname+'/'+name);return d.suggestedFilename()};
  const run=async(tool,id,fill)=>{await p.evaluate(([t,id])=>go('tool',{id:t,client:id}),[tool,id]);await p.waitForTimeout(200);if(fill)await fill();await p.screenshot({path:`F-form-${tool}.png`,fullPage:true});await p.click('#rf button[type=submit]');await p.waitForFunction(()=>S.runs[0].status!=='running');await p.waitForTimeout(300);return p.evaluate(()=>[UI.view,S.runs[0].status,S.runs[0].summary.slice(0,300)])};
  L('fee',await run('fee-comparison',ids.tan));await p.screenshot({path:'F-fee.png',fullPage:true});L(await dl('.doc [data-dl="0"]','FEE-test.docx'));
  L('soa',await run('soa',ids.tan));await p.click('[data-pv="0"]');await p.waitForTimeout(200);await p.screenshot({path:'F-soa.png',fullPage:true});L(await dl('.doc [data-dl="0"]','SOA-test.docx'));
  await p.click('[data-ok="0"]');await p.waitForTimeout(200);L('approved',await p.evaluate(()=>S.runs[0].status));
  L('roa',await run('roa',ids.pat,async()=>{await p.fill('#f-soa','2025-10-01')}));L(await dl('.doc [data-dl="0"]','ROA-test.docx'));
  L('tax',await run('tax-optimisation',ids.pat));await p.screenshot({path:'F-tax.png',fullPage:true});L(await dl('.doc [data-dl="0"]','TAX-test.docx'));
  L('review',await run('annual-review',ids.pat));L(await dl('.doc [data-dl="1"]','OFA-test.docx'));
  await p.click('[data-go="dashboard"]');await p.waitForTimeout(200);await p.screenshot({path:'F-dash.png',fullPage:true});
  await p.click('#askbtn');await p.waitForTimeout(200);L('opps',await p.$$eval('.opp h3',e=>e.map(x=>x.textContent)));await p.screenshot({path:'F-opps.png',fullPage:true});
  await p.fill('#q','hostplus');await p.press('#q','Enter');await p.waitForTimeout(200);L('search hostplus',await p.$$eval('main tbody tr td:first-child b',e=>e.map(x=>x.textContent)));
  await p.click('#packsave');await p.fill('#dlgin','correct horse 1');await p.fill('#dlgin2','correct horse 1');
  const [d4]=await Promise.all([p.waitForEvent('download'),p.click('dialog button[value=ok]')]);await d4.saveAs(__dirname+'/pack.json');
  const t=fs.readFileSync(__dirname+'/pack.json','utf8');L('pack encrypted',!/Tan|Patel|Hostplus/.test(t),t.length);
  await p.click('#reset');await p.click('dialog button[value=ok]');await p.waitForTimeout(200);L('after close',await p.evaluate(()=>S.clients.length));
  const [fc]=await Promise.all([p.waitForEvent('filechooser'),p.click('#packopen')]);await fc.setFiles(__dirname+'/pack.json');await p.fill('#dlgin','wrong pass 123');await p.click('dialog button[value=ok]');await p.waitForTimeout(800);L('wrong pass toast',await p.$eval('#toast',e=>e.textContent));
  const [fc2]=await Promise.all([p.waitForEvent('filechooser'),p.click('#packopen')]);await fc2.setFiles(__dirname+'/pack.json');await p.fill('#dlgin','correct horse 1');await p.click('dialog button[value=ok]');await p.waitForTimeout(1500);
  L('reopened',await p.evaluate(()=>[S.clients.map(c=>c.name),S.runs.length,S.runs.map(r=>r.status),Object.keys(DOCS).length,S.clients[0].nextReview instanceof Date||S.clients[0].nextReview===null]));
  await p.evaluate(()=>go('run',{id:S.runs.find(r=>r.tool==='soa').id}));await p.waitForTimeout(200);L(await dl('.doc [data-dl="0"]','SOA-reopened.docx'));
  await p.setViewportSize({width:390,height:844});await p.evaluate(()=>go('tools'));await p.waitForTimeout(200);L('mobile width',await p.evaluate(()=>document.documentElement.scrollWidth));
  L('errors',p.errs);await b.close()})().catch(e=>{console.log('FAILED',e.message);process.exit(1)});
