const { chromium } = require('playwright');const fs=require('fs');
const html=fs.readFileSync(require('path').join(__dirname,'..','brightly-live.html'),'utf8');
fs.writeFileSync(__dirname+'/live.html','<!doctype html><html><head><meta charset="utf-8"></head><body>'+html+'</body></html>');
const A=[1,2,3,4,5,6,7,8,9].map(i=>fs.existsSync(__dirname+`/recorded/answer${i}.txt`)?fs.readFileSync(__dirname+`/recorded/answer${i}.txt`,'utf8'):null);
const pickAns=p=>{if(p.includes('Sort them by client'))return p.includes('multiClient')?A[0]:A[1];
  if(p.includes('build a structured client profile'))return /Patel/.test(p.split('DOCUMENTS:')[1].slice(0,200))||/"Priya Patel"/.test(p.slice(0,200))?(A[2].includes('Patel')?A[2]:A[3]):(A[2].includes('Patel')?A[3]:A[2]);
  if(p.includes('Statement of Advice for Brightday'))return A[4];if(p.includes('Record of Advice'))return A[5];if(p.includes('annual review letter'))return A[6]||'{"opening":"Test","yearInReview":["a"],"portfolio":"p","objectives":[],"changes":[],"nextYear":["n"],"servicesDelivered":["s"],"confirm":[]}';
  return A[7]||'{"kind":"answer","title":"t","text":"x","clients":[]}'};
module.exports=async function setup(){const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',proxy:{server:process.env.HTTPS_PROXY},args:['--ignore-certificate-errors']});
  const ctx=await b.newContext({viewport:{width:1360,height:900},acceptDownloads:true});const p=await ctx.newPage();p.errs=[];p.on('pageerror',e=>p.errs.push(e.message));
  await p.exposeFunction('canned',async prompt=>pickAns(prompt));
  await p.addInitScript(()=>{window.claude={use:async n=>{if(n!=='sample')return null;const f=async()=>({text:''});
    f.json=async(input)=>{const out=await window.canned(typeof input==='string'?input:'');const s=out.slice(out.indexOf('{'),out.lastIndexOf('}')+1);return JSON.parse(s)};f.limits=async()=>({maxPromptBytes:262144});return f}}});
  await p.goto('file://'+__dirname+'/live.html');await p.click('#login .btn-primary');await p.waitForTimeout(300);
  await p.click('[data-go="clients"]');await p.click('#addc');
  const files=fs.readdirSync(__dirname+'/testdocs').filter(f=>!f.endsWith('.js')).map(f=>__dirname+'/testdocs/'+f);await p.setInputFiles('#impfile',files);
  await p.waitForFunction(()=>!IMP.busy&&IMP.order.length>=5,null,{timeout:60000});await p.click('#impsort');await p.waitForFunction(()=>!IMP.busy);await p.click('#impbuild');await p.waitForFunction(()=>IMP.stage==='done'||UI.view==='client');
  return{b,p}};
if(require.main===module)(async()=>{const {b,p}=await module.exports();
  console.log('clients',await p.evaluate(()=>S.clients.map(c=>c.name)));
  const tan=await p.evaluate(()=>S.clients.find(c=>/Tan/.test(c.name)).id);
  await p.evaluate(id=>go('tool',{id:'soa',client:id}),tan);await p.waitForTimeout(200);await p.click('#rf button[type=submit]');
  await p.waitForFunction(()=>S.runs[0].status!=='running');await p.waitForTimeout(300);
  console.log('view',await p.evaluate(()=>[UI.view,UI.params.id===S.runs[0].id,S.runs[0].status,S.runs[0].docs.length]));
  console.log('buttons',await p.$$eval('.doc button',e=>e.map(x=>x.outerHTML.slice(0,80))));
  console.log('errors',p.errs);await b.close()})();
